# Generated by Django 5.2.6 on 2026-09-28 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('core', '0002_documentcatalogitem_systemsetting_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_number', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=128)),
                ('birth_country', models.CharField(max_length=128)),
                ('parents_birth_place', models.CharField(max_length=128)),
                ('parents_birth_country', models.CharField(max_length=128)),
                ('document_type', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'identity_number'),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_number', models.CharField(max_length=32, unique=True)),
                ('submitted_on', models.DateField()),
                ('family_type', models.CharField(choices=[('with_children', 'Οικογένεια με τέκνα'), ('couple_no_children', 'Ζεύγος χωρίς τέκνα'), ('single_parent', 'Μονογονεϊκή οικογένεια'), ('other', 'Άλλο')], max_length=32)),
                ('family_type_other', models.CharField(blank=True, max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('declared_children_count', models.PositiveIntegerField(default=0)),
                ('recognized_dependent_children_count', models.PositiveIntegerField(default=0)),
                ('family_members_count', models.PositiveIntegerField(default=0)),
                ('person1_citizenship_cypriot', models.BooleanField(default=False)),
                ('person2_citizenship_cypriot', models.BooleanField(blank=True, null=True)),
                ('person1_relationship', models.CharField(default='Αιτητής', max_length=64)),
                ('person2_relationship', models.CharField(blank=True, max_length=64)),
                ('person1_residence_community', models.CharField(blank=True, max_length=255)),
                ('person2_residence_community', models.CharField(blank=True, max_length=255)),
                ('person1_residence_address', models.CharField(blank=True, max_length=255)),
                ('person2_residence_address', models.CharField(blank=True, max_length=255)),
                ('person1_residence_start', models.DateField(blank=True, null=True)),
                ('person2_residence_start', models.DateField(blank=True, null=True)),
                ('is_family_type_correct', models.BooleanField(blank=True, null=True)),
                ('corrected_family_type', models.CharField(blank=True, choices=[('with_children', 'Οικογένεια με τέκνα'), ('couple_no_children', 'Ζεύγος χωρίς τέκνα'), ('single_parent', 'Μονογονεϊκή οικογένεια'), ('other', 'Άλλο')], max_length=32)),
                ('signatures_status', models.CharField(blank=True, max_length=32)),
                ('completeness_result', models.CharField(blank=True, choices=[('complete', 'ΠΛΗΡΗΣ'), ('incomplete', 'ΜΗ ΠΛΗΡΗΣ')], max_length=16)),
                ('completeness_updated_at', models.DateTimeField(blank=True, null=True)),
                ('completeness_comments', models.TextField(blank=True)),
                ('outcome_104', models.CharField(choices=[('pass', "Κατ' αρχήν πληροί"), ('fail', "Κατ' αρχήν δεν πληροί"), ('pending', 'Εκκρεμεί έλεγχος')], default='pending', max_length=16)),
                ('submission_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cases.submissioncycle')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_person1', to='applications.person')),
                ('person2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_as_person2', to='applications.person')),
            ],
            options={
                'ordering': ('-submitted_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CommitteeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('eligible', 'Δικαιούχος'), ('not_eligible', 'Μη Δικαιούχος')], max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_decision', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DependentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('category', models.CharField(choices=[('minor', 'Ανήλικο'), ('student', 'Σπουδάζει'), ('national_guard', 'Εθνοφρουρός'), ('adult_disability', 'Ενήλικο άτομο με αναπηρία')], max_length=32)),
                ('is_recognized_dependent', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_children', to='applications.application')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_on', models.DateField()),
                ('is_on_time', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('ministry_letter_date', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('accepted', 'ΑΠΟΔΟΧΗ'), ('rejected', 'ΑΠΟΡΡΙΨΗ')], max_length=16)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.CharField(choices=[('10.4.1', '10.4.1 Κυπριακή υπηκοότητα'), ('10.4.2', '10.4.2 Ηλικία'), ('10.4.3', '10.4.3 Διαμονή'), ('10.4.4', '10.4.4 Άλλη ακίνητη ιδιοκτησία'), ('10.4.5', '10.4.5 Μη αποξένωση'), ('10.4.6', '10.4.6 Εισόδημα'), ('10.4.7', '10.4.7 Προηγούμενη κρατική ενίσχυση')], max_length=16)),
                ('person1_result', models.CharField(choices=[('pass', 'ΠΛΗΡΟΥΤΑΙ'), ('fail', 'ΔΕΝ ΠΛΗΡΟΥΤΑΙ'), ('pending', 'ΕΚΚΡΕΜΕΙ')], default='pending', max_length=16)),
                ('person2_result', models.CharField(blank=True, choices=[('pass', 'ΠΛΗΡΟΥΤΑΙ'), ('fail', 'ΔΕΝ ΠΛΗΡΟΥΤΑΙ'), ('pending', 'ΕΚΚΡΕΜΕΙ')], max_length=16)),
                ('overall_result', models.CharField(choices=[('pass', 'ΠΛΗΡΟΥΤΑΙ'), ('fail', 'ΔΕΝ ΠΛΗΡΟΥΤΑΙ'), ('pending', 'ΕΚΚΡΕΜΕΙ')], default='pending', max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='applications.application')),
            ],
            options={
                'ordering': ('criterion', 'id'),
                'unique_together': {('application', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('yes', 'ΝΑΙ'), ('no', 'ΟΧΙ'), ('not_required', 'ΔΕΝ ΑΠΑΙΤΕΙΤΑΙ')], max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='applications.application')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='core.documentcatalogitem')),
            ],
            options={
                'ordering': ('catalog_item__code', 'id'),
                'unique_together': {('application', 'catalog_item')},
            },
        ),
    ]
