# Generated by Django 5.2.6 on 2026-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='children_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='person1_has_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='person1_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='person1_non_alienation_clear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='person1_previous_aid_clear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='person2_has_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='person2_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='application',
            name='person2_non_alienation_clear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='person2_previous_aid_clear',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='residence_category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
