# Generated by Django 5.2.6 on 2026-09-28 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_documentcatalogitem_systemsetting_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(max_length=64, unique=True)),
                ('case_type', models.CharField(choices=[('new_division', 'Νέο αίτημα διαχωρισμού')], default='new_division', max_length=32)),
                ('start_date', models.DateField()),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.community')),
            ],
            options={
                'ordering': ('-start_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('suitability', 'Καταλληλότητα'), ('division', 'Διαχωρισμός')], max_length=16)),
                ('department', models.CharField(max_length=255)),
                ('topic', models.TextField(blank=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('received', 'Λήφθηκε'), ('closed', 'Κλείστηκε')], default='pending', max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='cases.case')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cases.case')),
            ],
            options={
                'ordering': ('code',),
                'unique_together': {('case', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InfrastructureCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_date', models.DateField()),
                ('curbs_ready', models.BooleanField(default=False)),
                ('pavements_ready', models.BooleanField(default=False)),
                ('asphalt_ready', models.BooleanField(default=False)),
                ('pavement_fill_ready', models.BooleanField(default=False)),
                ('water_ready', models.BooleanField(default=False)),
                ('telecom_ready', models.BooleanField(default=False)),
                ('electricity_ready', models.BooleanField(default=False)),
                ('street_light_ready', models.BooleanField(default=False)),
                ('is_ready_for_submission_cycle', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_checks', to='cases.case')),
            ],
            options={
                'ordering': ('-check_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel_number', models.CharField(max_length=64)),
                ('sheet_plan', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('ownership_status', models.CharField(blank=True, max_length=128)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('zone', models.CharField(blank=True, max_length=128)),
                ('inside_development_zone', models.BooleanField(default=False)),
                ('access', models.CharField(blank=True, max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('suitability_decision', models.CharField(blank=True, choices=[('suitable', 'Κατάλληλο'), ('conditional', 'Κατάλληλο υπό προϋποθέσεις'), ('unsuitable', 'Μη κατάλληλο')], max_length=16)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_plots', to='cases.case')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_person_id', models.IntegerField(blank=True, null=True)),
                ('lot_number_in_field', models.CharField(blank=True, max_length=64)),
                ('design_lot_number', models.CharField(blank=True, max_length=64)),
                ('tkx_lot_number', models.CharField(blank=True, max_length=64)),
                ('title_number', models.CharField(blank=True, max_length=64)),
                ('final_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('disposal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('comments', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='cases.case')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='cases.field')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_date', models.DateField()),
                ('submission_start_date', models.DateField()),
                ('submission_end_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_cycles', to='cases.case')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_cycles', to='core.community')),
            ],
            options={
                'ordering': ('-announcement_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionCyclePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('community', 'Αποστολή/ανάρτηση στην Κοινότητα ή στο Δ.Δ.'), ('district_office', 'Έντυπη ανάρτηση στα γραφεία Επαρχιακής Διοίκησης'), ('district_site', 'Ιστοσελίδα Επαρχιακής Διοίκησης'), ('ministry_site', 'Ιστοσελίδα ΥΠΕΣ'), ('other', 'Άλλο')], max_length=32)),
                ('published_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('submission_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='cases.submissioncycle')),
            ],
            options={
                'ordering': ('published_on', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=128)),
                ('proximity', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_services', to='cases.case')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ValuationReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=128)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_referrals', to='cases.case')),
            ],
            options={
                'ordering': ('-letter_date', '-id'),
            },
        ),
    ]
