# Generated by Django 5.2.6 on 2026-09-30 18:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def carry_forward_renamed_fields(apps, schema_editor):
    """Keep existing data when the case link becomes many-to-many (9.1).

    The old single-case link is copied into the new SubmissionCycle.cases set, and the
    conflated title/κοτσιάνι column is carried into the dedicated κοτσιάνι field (8.7).
    """
    SubmissionCycle = apps.get_model('cases', 'SubmissionCycle')
    for cycle in SubmissionCycle.objects.exclude(case_id=None).iterator():
        cycle.cases.add(cycle.case_id)

    Parcel = apps.get_model('cases', 'Parcel')
    for parcel in Parcel.objects.exclude(title_number='').iterator():
        parcel.kotsiani_number = parcel.title_number
        parcel.save(update_fields=['kotsiani_number'])


def reverse_renamed_fields(apps, schema_editor):
    SubmissionCycle = apps.get_model('cases', 'SubmissionCycle')
    for cycle in SubmissionCycle.objects.iterator():
        first_case = cycle.cases.first()
        if first_case is not None:
            cycle.case_id = first_case.pk
            cycle.save(update_fields=['case'])

    Parcel = apps.get_model('cases', 'Parcel')
    for parcel in Parcel.objects.exclude(kotsiani_number='').iterator():
        parcel.title_number = parcel.kotsiani_number
        parcel.save(update_fields=['title_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='access_technical_evaluation',
            field=models.TextField(blank=True, help_text='4.3 Τεχνική αξιολόγηση πρόσβασης στο/στα τεμάχιο/α'),
        ),
        migrations.AddField(
            model_name='case',
            name='contract_duration_unit',
            field=models.CharField(blank=True, choices=[('months', 'Μήνες'), ('years', 'Έτη')], help_text='8.5 Διάρκεια σύμβασης (μονάδα)', max_length=16),
        ),
        migrations.AddField(
            model_name='case',
            name='contract_duration_value',
            field=models.PositiveIntegerField(blank=True, help_text='8.5 Διάρκεια σύμβασης (αριθμός)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='contractor_email',
            field=models.EmailField(blank=True, help_text='8.5 Email αναδόχου', max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='contractor_name',
            field=models.CharField(blank=True, help_text='8.5 Ανάδοχος / πρόσωπο ανάθεσης', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='contractor_phone',
            field=models.CharField(blank=True, help_text='8.5 Τηλέφωνο αναδόχου', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='division_design_comments',
            field=models.TextField(blank=True, help_text='8.2 Σχόλια'),
        ),
        migrations.AddField(
            model_name='case',
            name='division_design_completed_on',
            field=models.DateField(blank=True, help_text='8.2 Ημερομηνία ολοκλήρωσης σχεδιασμού', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='division_design_plots_count',
            field=models.PositiveIntegerField(blank=True, help_text='8.2 Αριθμός οικοπέδων στον ολοκληρωμένο σχεδιασμό', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='division_design_status',
            field=models.CharField(blank=True, choices=[('pending', 'Εκκρεμεί'), ('completed', 'Ολοκληρώθηκε')], help_text='8.2 Κατάσταση σχεδιασμού', max_length=16),
        ),
        migrations.AddField(
            model_name='case',
            name='dls_application_date',
            field=models.DateField(blank=True, help_text='8.7 Ημερομηνία υποβολής αίτησης στο ΤΚΧ', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='dls_comments',
            field=models.TextField(blank=True, help_text='8.7 Σχόλια'),
        ),
        migrations.AddField(
            model_name='case',
            name='dls_file_number',
            field=models.CharField(blank=True, help_text='8.7 Αριθμός φακέλου ΤΚΧ', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='dls_response_date',
            field=models.DateField(blank=True, help_text='8.7 Ημερομηνία απάντησης / ολοκλήρωσης ΤΚΧ', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ministry_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Έγκριση'), ('rejected', 'Απόρριψη')], help_text='7 Απόφαση ΥΠΕΣ', max_length=16),
        ),
        migrations.AddField(
            model_name='case',
            name='ministry_response_date',
            field=models.DateField(blank=True, help_text='7 Ημερομηνία λήψης απάντησης ΥΠΕΣ', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_documentation',
            field=models.TextField(blank=True, help_text='1.2 Στοιχεία τεκμηρίωσης'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_limited_private_land',
            field=models.BooleanField(default=False, help_text='1.2 Μειωμένη διαθεσιμότητα ιδιωτικής γης για οικιστική ανάπτυξη'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_nuisance_developments',
            field=models.BooleanField(default=False, help_text='1.2 Οχληρές αναπτύξεις στα διοικητικά όρια της Κοινότητας'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_other',
            field=models.CharField(blank=True, help_text='1.2 Άλλο ιδιαίτερο χαρακτηριστικό (περιγραφή)', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_protection_zones',
            field=models.BooleanField(default=False, help_text='1.2 Επηρεασμός συνολικής έκτασης γης από Ζώνες Προστασίας'),
        ),
        migrations.AddField(
            model_name='case',
            name='priority_turkish_cypriot_properties',
            field=models.BooleanField(default=False, help_text='1.2 Μεγάλες εκτάσεις τουρκοκυπριακών περιουσιών'),
        ),
        migrations.AddField(
            model_name='case',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('positive', 'Θετική'), ('negative', 'Αρνητική')], help_text='7 Σύσταση Επαρχιακής Διοίκησης', max_length=16),
        ),
        migrations.AddField(
            model_name='case',
            name='recommendation_letter_date',
            field=models.DateField(blank=True, help_text='7 Ημερομηνία αποστολής επιστολής σύστασης', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='section2_comments',
            field=models.TextField(blank=True, help_text='2 Σχόλια / Παρατηρήσεις Ενότητας 2'),
        ),
        migrations.AddField(
            model_name='case',
            name='section3_comments',
            field=models.TextField(blank=True, help_text='3 Σχόλια / Παρατηρήσεις Ενότητας 3'),
        ),
        migrations.AddField(
            model_name='case',
            name='section4_comments',
            field=models.TextField(blank=True, help_text='4.5 Σχόλια / Παρατηρήσεις Ενότητας 4'),
        ),
        migrations.AddField(
            model_name='case',
            name='section6_comments',
            field=models.TextField(blank=True, help_text='6.7 Σχόλια / Παρατηρήσεις Ενότητας 6'),
        ),
        migrations.AddField(
            model_name='case',
            name='section7_comments',
            field=models.TextField(blank=True, help_text='7 Σχόλια / Παρατηρήσεις Ενότητας 7'),
        ),
        migrations.AddField(
            model_name='case',
            name='section8_comments',
            field=models.TextField(blank=True, help_text='8 Σχόλια / Παρατηρήσεις Ενότητας 8'),
        ),
        migrations.AddField(
            model_name='case',
            name='state_land_comments',
            field=models.TextField(blank=True, help_text='3 Σχόλια ελέγχου κρατικής γης'),
        ),
        migrations.AddField(
            model_name='case',
            name='state_land_remains_sufficient',
            field=models.CharField(blank=True, choices=[('yes', 'ΝΑΙ'), ('no', 'ΟΧΙ')], help_text='3 Παραμένουν ικανοποιητικές εκτάσεις κρατικής γης στην Κοινότητα', max_length=8),
        ),
        migrations.AddField(
            model_name='case',
            name='survey_assignment_comments',
            field=models.TextField(blank=True, help_text='8.1 Σχόλια'),
        ),
        migrations.AddField(
            model_name='case',
            name='survey_assignment_date',
            field=models.DateField(blank=True, help_text='8.1 Ημερομηνία ανάθεσης μελέτης', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='surveyor_email',
            field=models.EmailField(blank=True, help_text='8.1 Email χωρομέτρη', max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='surveyor_name',
            field=models.CharField(blank=True, help_text='8.1 Ονοματεπώνυμο ιδιώτη αρμόδιου χωρομέτρη', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='surveyor_phone',
            field=models.CharField(blank=True, help_text='8.1 Τηλέφωνο χωρομέτρη', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='tender_announcement_date',
            field=models.DateField(blank=True, help_text='8.5 Ημερομηνία προκήρυξης διαγωνισμού', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='tender_award_date',
            field=models.DateField(blank=True, help_text='8.5 Ημερομηνία κατακύρωσης', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='tender_comments',
            field=models.TextField(blank=True, help_text='8.5 Σχόλια'),
        ),
        migrations.AddField(
            model_name='case',
            name='tpo_application_date',
            field=models.DateField(blank=True, help_text='8.3 Ημερομηνία υποβολής αίτησης στο ΤΠΟ', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='tpo_application_number',
            field=models.CharField(blank=True, help_text='8.3 Αριθμός αίτησης ΤΠΟ', max_length=64),
        ),
        migrations.AddField(
            model_name='case',
            name='tpo_comments',
            field=models.TextField(blank=True, help_text='8.3 Σχόλια'),
        ),
        migrations.AddField(
            model_name='case',
            name='tpo_response',
            field=models.CharField(blank=True, choices=[('positive', 'Θετική'), ('conditional', 'Θετική υπό όρους'), ('negative', 'Αρνητική')], help_text='8.3 Απάντηση Διευθυντή ΤΠΟ', max_length=16),
        ),
        migrations.AddField(
            model_name='case',
            name='tpo_response_date',
            field=models.DateField(blank=True, help_text='8.3 Ημερομηνία απάντησης ΤΠΟ', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='works_progress_comments',
            field=models.TextField(blank=True, help_text='8.6 Σχόλια γενικής πορείας'),
        ),
        migrations.AddField(
            model_name='case',
            name='works_progress_stage',
            field=models.CharField(blank=True, help_text='8.6 Τρέχον στάδιο / πορεία εργασιών', max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='works_progress_updated_on',
            field=models.DateField(blank=True, help_text='8.6 Ημερομηνία ενημέρωσης πορείας', null=True),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='asphalt_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια οδοστρώματος', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='curbs_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια ρείθρων', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='electricity_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια ηλεκτρισμού', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='pavement_fill_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια επιχωμάτωσης', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='pavements_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια κρασπέδων', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='street_light_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια φωτισμού', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='telecom_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια τηλεπικοινωνιών', max_length=255),
        ),
        migrations.AddField(
            model_name='infrastructurecheck',
            name='water_comments',
            field=models.CharField(blank=True, help_text='8.6 Σχόλια υδατοπρομήθειας', max_length=255),
        ),
        migrations.AddField(
            model_name='landplot',
            name='estimated_plots_count',
            field=models.PositiveIntegerField(blank=True, help_text='4.1 Εκτιμώμενος αριθμός οικοπέδων', null=True),
        ),
        migrations.AddField(
            model_name='landplot',
            name='morphology',
            field=models.CharField(blank=True, choices=[('flat', 'Επίπεδο έδαφος'), ('mild', 'Ήπιες υψομετρικές διαφορές'), ('steep', 'Έντονες υψομετρικές διαφορές'), ('other', 'Άλλη τεχνική ιδιαιτερότητα')], help_text='4.1 Μορφολογία', max_length=16),
        ),
        migrations.AddField(
            model_name='landplot',
            name='morphology_comments',
            field=models.TextField(blank=True, help_text='4.1 Σχόλια Μορφολογίας'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='suitability_justification',
            field=models.TextField(blank=True, help_text='6.6 Αιτιολόγηση'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='technical_suitability',
            field=models.CharField(blank=True, choices=[('suitable', 'Κατάλληλο'), ('conditional', 'Κατάλληλο υπό προϋποθέσεις'), ('unsuitable', 'Μη κατάλληλο')], help_text='4.1 Τεχνική Καταλληλότητα', max_length=16),
        ),
        migrations.AddField(
            model_name='landplot',
            name='usable_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='4.1 Κατά προσέγγιση αξιοποιήσιμο εμβαδόν (τ.μ.)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='has_separate_title',
            field=models.CharField(blank=True, choices=[('yes', 'ΝΑΙ'), ('no', 'ΟΧΙ')], help_text='8.8.1 Υπάρχει ξεχωριστός Τίτλος Ιδιοκτησίας;', max_length=8),
        ),
        migrations.AddField(
            model_name='parcel',
            name='kotsiani_number',
            field=models.CharField(blank=True, help_text='8.7 Αριθμός κοτσιάνι (προαιρετικός)', max_length=64),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sheet_plan',
            field=models.CharField(blank=True, help_text='8.8 Φύλλο/Σχέδιο (αδιάθετα οικόπεδα)', max_length=64),
        ),
        migrations.AddField(
            model_name='parcel',
            name='valuation_referral',
            field=models.ForeignKey(blank=True, help_text='8.8 Παραπομπή προς Διευθυντή ΤΚΧ που καθόρισε την αξία', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='cases.valuationreferral'),
        ),
        migrations.AddField(
            model_name='submissioncycle',
            name='announcement_text',
            field=models.TextField(blank=True, help_text='9.3 Κείμενο ανακοίνωσης (αυτόματο προσχέδιο, επεξεργάσιμο)'),
        ),
        migrations.AddField(
            model_name='submissioncycle',
            name='cases',
            field=models.ManyToManyField(help_text='9.1 Υποθέσεις της ίδιας Κοινότητας που καλύπτει η γνωστοποίηση', related_name='submission_cycles', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(help_text='1.1 Μοναδικός αριθμός υπόθεσης', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('new_division', 'Νέο αίτημα διαχωρισμού'), ('unallocated_plots', 'Αδιάθετα οικόπεδα')], default='new_division', max_length=32),
        ),
        migrations.AlterField(
            model_name='case',
            name='comments',
            field=models.TextField(blank=True, help_text='1.3 Σχόλια / Παρατηρήσεις Ενότητας 1'),
        ),
        migrations.AlterField(
            model_name='case',
            name='contact_email',
            field=models.EmailField(help_text='1.1 Email επικοινωνίας Κ.Σ./Δ.Δ.', max_length=254),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(help_text='1.1 Ημερομηνία έναρξης διαδικασίας'),
        ),
        migrations.AlterField(
            model_name='case',
            name='submitted_at',
            field=models.DateField(blank=True, help_text='1.1 Ημερομηνία υποβολής αίτησης Κ.Σ./Δ.Δ.', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='comments',
            field=models.TextField(blank=True, help_text='5 / 8.4 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='department',
            field=models.CharField(help_text='5 / 8.4 Τμήμα / Υπηρεσία', max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='due_date',
            field=models.DateField(blank=True, help_text='5 / 8.4 Προθεσμία απάντησης', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='response_date',
            field=models.DateField(blank=True, help_text='5 / 8.4 Ημ. λήψης απάντησης', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='response_text',
            field=models.TextField(blank=True, help_text='5 / 8.4 Άποψη / Απάντηση'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sent_date',
            field=models.DateField(blank=True, help_text='5 / 8.4 Ημ. αποστολής', null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='stage',
            field=models.CharField(choices=[('suitability', 'Καταλληλότητα'), ('division', 'Διαχωρισμός')], help_text='5 / 8.4 Στάδιο', max_length=16),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Εκκρεμεί'), ('received', 'Λήφθηκε'), ('closed', 'Κλείστηκε')], default='pending', help_text='5 / 8.4 Κατάσταση (αυτόματη από την ημ. απάντησης)', max_length=16),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='topic',
            field=models.TextField(blank=True, help_text='5 / 8.4 Θέμα διαβούλευσης'),
        ),
        migrations.AlterField(
            model_name='field',
            name='code',
            field=models.CharField(help_text='8.7 Κωδικός χωραφιού', max_length=64),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, help_text='8.7 Περιγραφή χωραφιού', max_length=255),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='asphalt_ready',
            field=models.BooleanField(default=False, help_text='8.6 Ασφαλτοστρωμένο οδόστρωμα'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='check_date',
            field=models.DateField(help_text='8.6 Ημερομηνία ελέγχου'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='comments',
            field=models.TextField(blank=True, help_text='8.6 Σχόλια ελέγχου'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='curbs_ready',
            field=models.BooleanField(default=False, help_text='8.6 Ρείθρα'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='electricity_ready',
            field=models.BooleanField(default=False, help_text='8.6 Παροχή ηλεκτρικού ρεύματος'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='is_ready_for_submission_cycle',
            field=models.BooleanField(default=False, help_text='8.6 Συνολικό ΝΑΙ/ΟΧΙ ετοιμότητας για άνοιγμα κύκλου υποβολής (αυτόματο)'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='pavement_fill_ready',
            field=models.BooleanField(default=False, help_text='8.6 Επιχωμάτωση πεζοδρομίων'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='pavements_ready',
            field=models.BooleanField(default=False, help_text='8.6 Κράσπεδα'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='street_light_ready',
            field=models.BooleanField(default=False, help_text='8.6 Οδικός φωτισμός'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='telecom_ready',
            field=models.BooleanField(default=False, help_text='8.6 Τηλεπικοινωνίες'),
        ),
        migrations.AlterField(
            model_name='infrastructurecheck',
            name='water_ready',
            field=models.BooleanField(default=False, help_text='8.6 Υδατοπρομήθεια'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='access',
            field=models.CharField(blank=True, help_text='3.1 Πρόσβαση', max_length=128),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='3.1 Εμβαδόν (τ.μ.)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='comments',
            field=models.TextField(blank=True, help_text='3.1 Σχόλια τεμαχίου'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='inside_development_zone',
            field=models.BooleanField(default=False, help_text='3.1 Εντός Ορίου Ανάπτυξης'),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='location',
            field=models.CharField(blank=True, help_text='3.1 Τοποθεσία', max_length=255),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='ownership_status',
            field=models.CharField(blank=True, help_text='3.1 Ιδιοκτησιακό καθεστώς', max_length=128),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='parcel_number',
            field=models.CharField(help_text='3.1 Αρ. τεμαχίου', max_length=64),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='sheet_plan',
            field=models.CharField(blank=True, help_text='3.1 Φύλλο/Σχέδιο', max_length=64),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='suitability_decision',
            field=models.CharField(blank=True, choices=[('suitable', 'Κατάλληλο'), ('conditional', 'Κατάλληλο υπό προϋποθέσεις'), ('unsuitable', 'Μη κατάλληλο')], help_text='6.6 Απόφαση Καταλληλότητας', max_length=16),
        ),
        migrations.AlterField(
            model_name='landplot',
            name='zone',
            field=models.CharField(blank=True, help_text='3.1 Πολεοδομική Ζώνη', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='comments',
            field=models.TextField(blank=True, help_text='8.7 Σχόλια οικοπέδου'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='design_lot_number',
            field=models.CharField(blank=True, help_text='8.7 Αρ. οικοπέδου στον εγκεκριμένο σχεδιασμό', max_length=64),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='disposal_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='8.8 Τιμή διάθεσης (αυτόματα 25% της αξίας)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field',
            field=models.ForeignKey(blank=True, help_text='8.7 Χωράφι προέλευσης (προαιρετικό)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='cases.field'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='final_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='8.7 Τελικό εμβαδόν (τ.μ.)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='lot_number_in_field',
            field=models.CharField(blank=True, help_text='8.7 Νούμερο εντός χωραφιού (προαιρετικό)', max_length=64),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='owner_person_id',
            field=models.IntegerField(blank=True, help_text='8.7 Ιδιοκτήτης (Person)', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tkx_lot_number',
            field=models.CharField(blank=True, help_text='8.7 Αρ. οικοπέδου ΤΚΧ', max_length=64),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='valuation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='8.8 Αξία για υπολογισμό', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='submissioncycle',
            name='announcement_date',
            field=models.DateField(help_text='9.1 Ημερομηνία γνωστοποίησης'),
        ),
        migrations.AlterField(
            model_name='submissioncycle',
            name='comments',
            field=models.TextField(blank=True, help_text='9.5 Σχόλια / Παρατηρήσεις Ενότητας 9'),
        ),
        migrations.AlterField(
            model_name='submissioncycle',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='9.3 Οριστικοποίηση / έκδοση ανακοίνωσης', null=True),
        ),
        migrations.AlterField(
            model_name='submissioncycle',
            name='submission_end_date',
            field=models.DateField(help_text='9.1 Λήξη υποβολής αιτήσεων'),
        ),
        migrations.AlterField(
            model_name='submissioncycle',
            name='submission_start_date',
            field=models.DateField(help_text='9.1 Έναρξη υποβολής αιτήσεων'),
        ),
        migrations.AlterField(
            model_name='utilityservice',
            name='comments',
            field=models.TextField(blank=True, help_text='4.2 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='utilityservice',
            name='proximity',
            field=models.CharField(blank=True, help_text='4.2 Εγγύτητα με το/τα τεμάχιο/α', max_length=255),
        ),
        migrations.AlterField(
            model_name='utilityservice',
            name='service_name',
            field=models.CharField(help_text='4.2 Υπηρεσία', max_length=128),
        ),
        migrations.AlterField(
            model_name='valuationreferral',
            name='comments',
            field=models.TextField(blank=True, help_text='8.8 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='valuationreferral',
            name='letter_date',
            field=models.DateField(blank=True, help_text='8.8 Ημερομηνία επιστολής / αίτησης προς ΤΚΧ', null=True),
        ),
        migrations.AlterField(
            model_name='valuationreferral',
            name='reference_number',
            field=models.CharField(blank=True, help_text='8.8 Αριθμός φακέλου / αναφοράς', max_length=128),
        ),
        migrations.AlterField(
            model_name='valuationreferral',
            name='response_date',
            field=models.DateField(blank=True, help_text='8.8 Ημερομηνία απάντησης ΤΚΧ', null=True),
        ),
        migrations.CreateModel(
            name='CompletenessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(help_text='2 Αύξουσα αρίθμηση ελέγχου (1ος, 2ος, …)')),
                ('check_date', models.DateField(help_text='2 Ημερομηνία ελέγχου')),
                ('result', models.CharField(choices=[('yes', 'ΝΑΙ'), ('no', 'ΟΧΙ')], help_text='2 Η αίτηση Κ.Σ., τα απαιτούμενα στοιχεία και ο κατάλογος ≥10 οικογενειών είναι πλήρη', max_length=8)),
                ('deficiencies', models.TextField(blank=True, help_text='2 Ελλείψεις / Απαιτούμενα συμπληρωματικά στοιχεία (όταν ΟΧΙ)')),
                ('comments', models.TextField(blank=True, help_text='2 Σχόλια ελέγχου')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completeness_checks', to='cases.case')),
            ],
            options={
                'ordering': ('-sequence', '-id'),
                'unique_together': {('case', 'sequence')},
            },
        ),
        migrations.RunPython(carry_forward_renamed_fields, reverse_renamed_fields),
        migrations.RemoveField(
            model_name='submissioncycle',
            name='case',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='title_number',
        ),
    ]
