# Generated by Django 5.2.6 on 2026-09-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_parcel_title_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioncyclepublication',
            name='method',
            field=models.CharField(choices=[('community', 'Αποστολή/ανάρτηση στην Κοινότητα ή στο Δ.Δ.'), ('district_office', 'Έντυπη ανάρτηση στα γραφεία Επαρχιακής Διοίκησης'), ('district_site', 'Ιστοσελίδα Επαρχιακής Διοίκησης'), ('ministry_site', 'Ιστοσελίδα ΥΠΕΣ'), ('other', 'Άλλο')], help_text='9.2 Τρόπος δημοσίευσης', max_length=32),
        ),
        migrations.AlterField(
            model_name='submissioncyclepublication',
            name='notes',
            field=models.CharField(blank=True, help_text='9.2 Διευκρίνιση «Άλλο» / σημειώσεις', max_length=255),
        ),
        migrations.AlterField(
            model_name='submissioncyclepublication',
            name='published_on',
            field=models.DateField(help_text='9.2 Ημερομηνία δημοσίευσης'),
        ),
    ]
