# Generated by Django 5.2.6 on 2026-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_section3_land_plot_choices_and_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='landplot',
            name='morphology_other',
            field=models.CharField(blank=True, help_text='4.1 Περιγραφή άλλης τεχνικής ιδιαιτερότητας', max_length=255),
        ),
    ]
