# Generated by Django 5.2.6 on 2026-10-01 10:25

from django.db import migrations


def move_case_emails_to_checks(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    CompletenessCheck = apps.get_model("cases", "CompletenessCheck")
    Communication = apps.get_model("core", "Communication")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias

    case_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="cases", model="case"
    )
    check_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="cases", model="completenesscheck"
    )

    case_ids = (
        Communication.objects.using(db_alias)
        .filter(content_type_id=case_ct.pk)
        .values_list("object_id", flat=True)
        .distinct()
    )
    latest_check_by_case = {}
    for check in (
        CompletenessCheck.objects.using(db_alias)
        .filter(case_id__in=case_ids)
        .order_by("case_id", "-check_date", "-sequence", "-id")
    ):
        latest_check_by_case.setdefault(check.case_id, check.pk)

    communications = Communication.objects.using(db_alias).filter(content_type_id=case_ct.pk)
    for communication in communications.iterator():
        check_id = latest_check_by_case.get(communication.object_id)
        if not check_id:
            continue
        communication.content_type_id = check_ct.pk
        communication.object_id = check_id
        communication.save(update_fields=["content_type", "object_id", "updated_at"])


def move_check_emails_back_to_case(apps, schema_editor):
    CompletenessCheck = apps.get_model("cases", "CompletenessCheck")
    Communication = apps.get_model("core", "Communication")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias

    case_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="cases", model="case"
    )
    check_ct, _ = ContentType.objects.using(db_alias).get_or_create(
        app_label="cases", model="completenesscheck"
    )
    checks = {
        check.pk: check.case_id for check in CompletenessCheck.objects.using(db_alias).all()
    }
    communications = Communication.objects.using(db_alias).filter(content_type_id=check_ct.pk)
    for communication in communications.iterator():
        case_id = checks.get(communication.object_id)
        if not case_id:
            continue
        communication.content_type_id = case_ct.pk
        communication.object_id = case_id
        communication.save(update_fields=["content_type", "object_id", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_seed_case_section_labels"),
        ("cases", "0005_section4_morphology_other"),
    ]

    operations = [
        migrations.RunPython(move_case_emails_to_checks, move_check_emails_back_to_case),
    ]
