# Generated by Django 5.2.6 on 2026-10-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_section2_email_per_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completenesscheck',
            options={'ordering': ('-check_date', '-sequence', '-id')},
        ),
        migrations.AlterField(
            model_name='case',
            name='priority_documentation',
            field=models.TextField(blank=True, help_text='1.2 Σχόλια/Παρατηρήσεις'),
        ),
    ]
