# Generated by Django 5.2.6 on 2026-10-01 12:28

from django.db import migrations, models


def _normalize_department(value):
    return (value or "").upper().replace(".", "").replace(" ", "")


def migrate_consultation_departments(apps, schema_editor):
    Consultation = apps.get_model("cases", "Consultation")
    mapping = {
        "ΤΚΧ": "tkx",
        "TKX": "tkx",
        "ΤΑΥ": "tay",
        "TAY": "tay",
        "ΑΗΚ": "ahk",
        "AHK": "ahk",
        "TKX": "tkx",
        "TAY": "tay",
        "AHK": "ahk",
    }
    for consultation in Consultation.objects.all():
        raw = (consultation.department or "").strip()
        key = _normalize_department(raw)
        if key in mapping:
            consultation.department = mapping[key]
            consultation.department_other = ""
        elif raw in ("tkx", "tay", "ahk", "other"):
            consultation.department_other = consultation.department_other or ""
        else:
            consultation.department = "other"
            consultation.department_other = raw
        consultation.save(update_fields=["department", "department_other"])


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_technical_visit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='department_other',
            field=models.CharField(blank=True, help_text='5 / 8.4 Περιγραφή όταν Τμήμα / Υπηρεσία = Άλλο', max_length=255),
        ),
        migrations.RunPython(migrate_consultation_departments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='consultation',
            name='department',
            field=models.CharField(choices=[('tkx', 'Τ.Κ.Χ'), ('tay', 'Τ.Α.Υ'), ('ahk', 'Α.Η.Κ'), ('other', 'Άλλο')], help_text='5 / 8.4 Τμήμα / Υπηρεσία', max_length=16),
        ),
    ]
