# Generated by Django 5.2.6 on 2026-10-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_consultation_department_and_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='section6_comments',
        ),
    ]
