# Generated by Django 5.2.6 on 2026-10-03 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_case_ministry_fields_to_rounds(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    MinistryDecisionRound = apps.get_model("cases", "MinistryDecisionRound")
    for case in Case.objects.all().iterator():
        if not any(
            [
                case.recommendation_letter_date,
                case.recommendation,
                case.ministry_response_date,
                case.ministry_decision,
                (case.section7_comments or "").strip(),
            ]
        ):
            continue
        MinistryDecisionRound.objects.create(
            case_id=case.pk,
            letter_sent_date=case.recommendation_letter_date,
            recommendation=case.recommendation or "",
            ministry_response_date=case.ministry_response_date,
            ministry_decision=case.ministry_decision or "",
            comments=case.section7_comments or "",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_remove_case_section6_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryDecisionRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "letter_sent_date",
                    models.DateField(blank=True, help_text="6.7 Ημερομηνία αποστολής", null=True),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Θετική"),
                            ("negative", "Αρνητική"),
                            ("other", "Άλλο"),
                        ],
                        help_text="6.7 Σύσταση Επαρχιακής Διοίκησης",
                        max_length=16,
                    ),
                ),
                (
                    "recommendation_other",
                    models.CharField(
                        blank=True,
                        help_text="6.7 Σύσταση Επαρχιακής Διοίκησης — Άλλο",
                        max_length=255,
                    ),
                ),
                (
                    "ministry_response_date",
                    models.DateField(blank=True, help_text="6.7 Ημερομηνία λήψης απάντησης", null=True),
                ),
                (
                    "ministry_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Έγκριση"),
                            ("rejected", "Απόρριψη"),
                            ("other", "Άλλο"),
                        ],
                        help_text="6.7 Απόφαση ΥΠΕΣ",
                        max_length=16,
                    ),
                ),
                (
                    "ministry_decision_other",
                    models.CharField(
                        blank=True, help_text="6.7 Απόφαση ΥΠΕΣ — Άλλο", max_length=255
                    ),
                ),
                ("comments", models.TextField(blank=True, help_text="6.7 Σχόλια / Παρατηρήσεις")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_decision_rounds",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.RunPython(migrate_case_ministry_fields_to_rounds, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="case",
            name="ministry_decision",
        ),
        migrations.RemoveField(
            model_name="case",
            name="ministry_response_date",
        ),
        migrations.RemoveField(
            model_name="case",
            name="recommendation",
        ),
        migrations.RemoveField(
            model_name="case",
            name="recommendation_letter_date",
        ),
        migrations.RemoveField(
            model_name="case",
            name="section7_comments",
        ),
    ]
