# Generated by Django 5.2.6 on 2026-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_ministry_decision_round_attachment_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='division_design_comments',
            field=models.TextField(blank=True, help_text='7.2 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='case',
            name='division_design_completed_on',
            field=models.DateField(blank=True, help_text='7.2 Ημερομηνία ολοκλήρωσης σχεδιασμού', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='division_design_plots_count',
            field=models.PositiveIntegerField(blank=True, help_text='7.2 Αριθμός οικοπέδων', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='division_design_status',
            field=models.CharField(blank=True, choices=[('pending', 'Εκκρεμεί'), ('completed', 'Ολοκληρώθηκε')], help_text='7.2 Κατάσταση σχεδιασμού', max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='survey_assignment_comments',
            field=models.TextField(blank=True, help_text='7.1 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='case',
            name='survey_assignment_date',
            field=models.DateField(blank=True, help_text='7.1 Ημερομηνία ανάθεσης μελέτης', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='surveyor_email',
            field=models.EmailField(blank=True, help_text='7.1 Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='case',
            name='surveyor_name',
            field=models.CharField(blank=True, help_text='7.1 Ονοματεπώνυμο ιδιώτη αρμόδιου χωρομέτρη', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='surveyor_phone',
            field=models.CharField(blank=True, help_text='7.1 Τηλέφωνο', max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='tpo_application_date',
            field=models.DateField(blank=True, help_text='7.3 Ημερομηνία υποβολής αίτησης στο ΤΠΟ', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tpo_application_number',
            field=models.CharField(blank=True, help_text='7.3 Αριθμός αίτησης ΤΠΟ', max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='tpo_comments',
            field=models.TextField(blank=True, help_text='7.3 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tpo_response',
            field=models.CharField(blank=True, choices=[('positive', 'Θετική'), ('conditional', 'Θετική υπό όρους'), ('negative', 'Αρνητική')], help_text='7.3 Απάντηση Διευθυντή ΤΠΟ', max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='tpo_response_date',
            field=models.DateField(blank=True, help_text='7.3 Ημερομηνία απάντησης ΤΠΟ', null=True),
        ),
    ]
