# Generated by Django 5.2.6 on 2026-10-03 14:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_section7_subsection_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDesignPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot_type', models.CharField(choices=[('division_plot', 'Υπό διαχωρισμό οικόπεδο'), ('green_space', 'Χώρος πρασίνου'), ('eac_substation', 'Υποσταθμός ΑΗΚ'), ('community_facility', 'Χώρος κοινοτικού εξοπλισμού'), ('other', 'Άλλο')], help_text='7.3 Τύπος', max_length=32)),
                ('plot_type_other', models.CharField(blank=True, help_text='7.3 Τύπος — Άλλο', max_length=255)),
                ('design_number', models.CharField(blank=True, help_text='7.3 Αρίθμηση', max_length=64)),
                ('tkx_number', models.CharField(blank=True, help_text='7.3 Αρίθμηση ΤΚΧ', max_length=64)),
                ('title_deed_number', models.CharField(blank=True, help_text='7.3 Αριθμός τίτλου ιδιοκτησίας', max_length=64)),
                ('parcel_number', models.CharField(blank=True, help_text='7.3 Αριθμός τεμαχίου', max_length=64)),
                ('sheet_plan', models.CharField(blank=True, help_text='7.3 Φύλλο/Σχέδιο', max_length=64)),
                ('numbering_status', models.CharField(choices=[('design', 'Αρίθμηση σχεδιασμού'), ('tkx', 'Αρίθμηση ΤΚΧ'), ('title_deed', 'Αρίθμηση βάσει τίτλου ιδιοκτησίας')], default='design', help_text='7.3 Κατάσταση αρίθμησης', max_length=16)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_design_plots', to='cases.case')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
