# Generated by Django 5.2.6 on 2026-10-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_approved_design_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveddesignplot',
            name='final_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='7.3 Τελικό εμβαδόν (τ.μ.)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract_duration_unit',
            field=models.CharField(blank=True, choices=[('months', 'Μήνες'), ('years', 'Έτη')], help_text='7.7 Διάρκεια σύμβασης (μονάδα)', max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract_duration_value',
            field=models.PositiveIntegerField(blank=True, help_text='7.7 Διάρκεια σύμβασης (αριθμός)', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='contractor_email',
            field=models.EmailField(blank=True, help_text='7.7 Email αναδόχου', max_length=254),
        ),
        migrations.AlterField(
            model_name='case',
            name='contractor_name',
            field=models.CharField(blank=True, help_text='7.7 Ανάδοχος / πρόσωπο ανάθεσης', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='contractor_phone',
            field=models.CharField(blank=True, help_text='7.7 Τηλέφωνο αναδόχου', max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='section8_comments',
            field=models.TextField(blank=True, help_text='7.7 Σχόλια / Παρατηρήσεις Ενότητας 7'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tender_announcement_date',
            field=models.DateField(blank=True, help_text='7.7 Ημερομηνία προκήρυξης διαγωνισμού', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tender_award_date',
            field=models.DateField(blank=True, help_text='7.7 Ημερομηνία κατακύρωσης', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tender_comments',
            field=models.TextField(blank=True, help_text='7.7 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_comments',
            field=models.TextField(blank=True, help_text='7.7 Σχόλια γενικής πορείας'),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_stage',
            field=models.CharField(blank=True, help_text='7.7 Τρέχον στάδιο / πορεία εργασιών', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_updated_on',
            field=models.DateField(blank=True, help_text='7.7 Ημερομηνία ενημέρωσης πορείας', null=True),
        ),
    ]
