# Generated by Django 5.2.6 on 2026-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_approved_design_plot_final_area_section_7_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='construction_plans_stage',
            field=models.TextField(blank=True, help_text='7.4 Στάδιο κατασκευαστικών σχεδίων'),
        ),
        migrations.AddField(
            model_name='case',
            name='land_expropriation_required',
            field=models.CharField(blank=True, choices=[('yes', 'ΝΑΙ'), ('no', 'ΟΧΙ')], help_text='7.4 Απαιτείται απαλλοτρίωση γης', max_length=8),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='stage',
            field=models.CharField(choices=[('suitability', 'Καταλληλότητα'), ('division', 'Κατασκευαστικά σχέδια')], help_text='5 / 8.4 Στάδιο', max_length=16),
        ),
    ]
