# Generated by Django 5.2.6 on 2026-10-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_case_construction_plans_7_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='contract_duration_unit',
            field=models.CharField(blank=True, choices=[('months', 'Μήνες'), ('years', 'Έτη')], help_text='7.5 Διάρκεια σύμβασης (μονάδα)', max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract_duration_value',
            field=models.PositiveIntegerField(blank=True, help_text='7.5 Διάρκεια σύμβασης (αριθμός)', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='contractor_email',
            field=models.EmailField(blank=True, help_text='7.5 Email αναδόχου', max_length=254),
        ),
        migrations.AlterField(
            model_name='case',
            name='contractor_name',
            field=models.CharField(blank=True, help_text='7.5 Ανάδοχος / πρόσωπο ανάθεσης', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='contractor_phone',
            field=models.CharField(blank=True, help_text='7.5 Τηλέφωνο αναδόχου', max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='tender_announcement_date',
            field=models.DateField(blank=True, help_text='7.5 Ημερομηνία προκήρυξης διαγωνισμού', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tender_award_date',
            field=models.DateField(blank=True, help_text='7.5 Ημερομηνία κατακύρωσης', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='tender_comments',
            field=models.TextField(blank=True, help_text='7.5 Σχόλια'),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_stage',
            field=models.CharField(blank=True, help_text='7.7 Τρέχον στάδιο / γενική πορεία εργασιών', max_length=255),
        ),
    ]
