# Generated by Django 5.2.6 on 2026-10-04 12:40

from django.db import migrations, models


def set_contract_duration_unit_to_months(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    Case.objects.all().update(contract_duration_unit="months")


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_case_contract_duration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='contract_duration_unit',
            field=models.CharField(blank=True, choices=[('months', 'Μήνες'), ('years', 'Έτη')], help_text='7.5 Διάρκεια σύμβασης (μονάδα - πάντα μήνες)', max_length=16),
        ),
        migrations.AlterField(
            model_name='case',
            name='contract_duration_value',
            field=models.PositiveIntegerField(blank=True, help_text='7.5 Διάρκεια σύμβασης (μήνες)', null=True),
        ),
        migrations.RunPython(set_contract_duration_unit_to_months, migrations.RunPython.noop),
    ]
