# Generated by Django 5.2.6 on 2026-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_alter_case_contract_duration_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='section8_comments',
            field=models.TextField(blank=True, help_text='7.6 Σχόλια / Παρατηρήσεις Ενότητας 7'),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_comments',
            field=models.TextField(blank=True, help_text='7.6 Σχόλια γενικής πορείας'),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_stage',
            field=models.CharField(blank=True, help_text='7.6 Τρέχον στάδιο / γενική πορεία εργασιών', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='works_progress_updated_on',
            field=models.DateField(blank=True, help_text='7.6 Ημερομηνία ενημέρωσης πορείας', null=True),
        ),
    ]
