# Generated by Django 5.2.6 on 2026-09-28 19:51

from django.db import migrations
from django.db.models import Q


def create_default_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    role_names = [
        "Λειτουργός καταχώρισης",
        "Προϊστάμενος ελέγχου",
        "Μέλος Επιτροπής",
        "Έπαρχος",
        "Διαχειριστής",
        "Μόνο ανάγνωση",
    ]
    groups = {}
    for role_name in role_names:
        group, _ = Group.objects.get_or_create(name=role_name)
        groups[role_name] = group

    add_change_view = Permission.objects.filter(
        Q(codename__startswith="add_")
        | Q(codename__startswith="change_")
        | Q(codename__startswith="view_")
    )
    view_only = Permission.objects.filter(codename__startswith="view_")

    for group in groups.values():
        group.permissions.clear()

    groups["Διαχειριστής"].permissions.set(add_change_view)
    groups["Λειτουργός καταχώρισης"].permissions.set(add_change_view)
    groups["Προϊστάμενος ελέγχου"].permissions.set(add_change_view)
    groups["Μέλος Επιτροπής"].permissions.set(view_only)
    groups["Έπαρχος"].permissions.set(view_only)
    groups["Μόνο ανάγνωση"].permissions.set(view_only)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentcatalogitem_systemsetting_community'),
    ]

    operations = [migrations.RunPython(create_default_roles, migrations.RunPython.noop)]
