# Generated by Django 5.2.6 on 2026-09-28 19:52

from django.db import migrations


def seed_default_system_settings(apps, schema_editor):
    SystemSetting = apps.get_model("core", "SystemSetting")
    defaults = [
        ("applicationFolderPrefix", "12", "Prefix για Αρ. Φακέλου Αιτητή"),
        ("folderSequenceDigits", "3", "Πλήθος ψηφίων αύξοντος ανά Κοινότητα"),
    ]
    for key, value, description in defaults:
        SystemSetting.objects.update_or_create(
            key=key,
            defaults={"value": value, "description": description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_roles'),
    ]

    operations = [
        migrations.RunPython(seed_default_system_settings, migrations.RunPython.noop),
    ]
