# Generated by Django 5.2.6 on 2026-10-01 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_case_section_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_key', models.CharField(max_length=128)),
                ('reminder_type', models.CharField(max_length=64)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-read_at', '-id'),
                'unique_together': {('user', 'reminder_key')},
            },
        ),
    ]
