# Generated by Django 5.2.6 on 2026-10-01 14:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_app_title_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ονομασία ρόλου', max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, help_text='Ενεργός (ανενεργός ρόλος δεν δίνει πρόσβαση)')),
                ('grants', models.JSONField(blank=True, default=list)),
                ('members', models.ManyToManyField(blank=True, related_name='app_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
