# Generated by Django 5.2.6 on 2026-09-28 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('cases', '0001_initial'),
        ('core', '0002_documentcatalogitem_systemsetting_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ενεργή'), ('cancelled', 'Ακυρώθηκε')], default='active', max_length=16)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='applications.application')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cases.parcel')),
            ],
            options={
                'ordering': ('-allocated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('signed', 'ΥΠΟΓΡΑΦΗΚΕ'), ('not_signed', 'ΔΕΝ ΥΠΟΓΡΑΦΗΚΕ')], default='not_signed', max_length=16)),
                ('template_version', models.CharField(blank=True, max_length=64)),
                ('comments', models.TextField(blank=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='allocation.allocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConstructionMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('two_year_check_done', models.BooleanField(default=False)),
                ('two_year_result', models.CharField(blank=True, choices=[('in_progress', 'Σε εξέλιξη'), ('completed', 'Ολοκληρωμένη'), ('not_started', 'Δεν έχει προχωρήσει')], max_length=16)),
                ('three_year_check_done', models.BooleanField(default=False)),
                ('housing_completed', models.BooleanField(default=False)),
                ('extension_granted', models.BooleanField(default=False)),
                ('new_deadline', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='construction_monitoring', to='allocation.agreement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lottery_type', models.CharField(choices=[('rank_tie', 'Κλήρωση ισοψηφίας κατάταξης'), ('parcel_allocation', 'Κλήρωση κατανομής οικοπέδων')], max_length=32)),
                ('lottery_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotteries', to='core.community')),
                ('submission_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotteries', to='cases.submissioncycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='lottery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='allocation.lottery'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'ΠΛΗΡΩΘΗΚΕ'), ('pending', 'ΕΚΚΡΕΜΕΙ')], default='pending', max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='allocation.allocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_type', models.CharField(choices=[('preliminary', 'Προκαταρκτικός'), ('final', 'Τελικός')], max_length=16)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_id', models.IntegerField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_lists', to='core.community')),
                ('submission_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_lists', to='cases.submissioncycle')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('submission_cycle', 'list_type')},
            },
        ),
        migrations.CreateModel(
            name='TitleTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('title_number', models.CharField(blank=True, max_length=64)),
                ('title_issue_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_transfer', to='allocation.allocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('finalized_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('eligible', 'Δικαιούχος'), ('alternate', 'Επιλαχών')], max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entries', to='applications.application')),
                ('ranking_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='allocation.rankinglist')),
            ],
            options={
                'ordering': ('finalized_rank', 'proposed_rank', 'id'),
                'unique_together': {('ranking_list', 'application')},
            },
        ),
    ]
